## 00. PyTorch Fundamentals

* [Resource notebook](https://www.learnpytorch.io/00_pytorch_fundamentals/)
* [Additional resources](https://pytorch.org/tutorials/beginner/basics/intro.html)

In [1]:
# Loading dependecies
import torch

In [2]:
print(torch.__version__)

2.5.1+cu118


## Introduction of tensors

> In mathematics, a tensor is an algebraic object that describes a multilinear relationship between sets of algebraic objects related to a vector space. Tensors may map between different objects such as vectors, scalars, and even other tensors. There are many types of tensors, including scalars and vectors (which are the simplest tensors), dual vectors, multilinear maps between vector spaces, and even some operations such as the dot product.
(...)
A tensor may be represented as a (potentially multidimensional) array.
[Reference](https://en.wikipedia.org/wiki/Tensor).

Creating tensors

[torch.Tensor](https://pytorch.org/docs/stable/tensors.html#torch-tensor)

In [3]:
# Scalar
scalar = torch.tensor(7)
print(f"To get scalar as int: {scalar.item()}")
print(f"To get scalar dimension: {scalar.ndim}")

To get scalar as int: 7
To get scalar dimension: 0


In [4]:
# Vector
vector = torch.tensor([7, 8]) # [magnitud, direction] -> vector!
print(f"To get vector: {vector}")
print(f"To get vector shape: {vector.shape}")
print(f"To get vector dimension: {vector.ndim}")

To get vector: tensor([7, 8])
To get vector shape: torch.Size([2])
To get vector dimension: 1


In [5]:
# MATRIX
MATRIX = torch.tensor([[1, 5], [9, 3], [7, 8]])
print(f"To get MATRIX: {MATRIX}")
print(f"To get MATRIX dimension: {MATRIX.ndim}")
print(f"To get MATRIX shape: {MATRIX.shape}")  # Rows, Columns
print(f"To get MATRIX first element: {MATRIX[0]}")
print(f"To get MATRIX second element: {MATRIX[1]}")

To get MATRIX: tensor([[1, 5],
        [9, 3],
        [7, 8]])
To get MATRIX dimension: 2
To get MATRIX shape: torch.Size([3, 2])
To get MATRIX first element: tensor([1, 5])
To get MATRIX second element: tensor([9, 3])


In [6]:
# TENSOR
TENSOR = torch.tensor([[[1, 5, 8], [9, 3, 9], [7, 8, 2]], [[5, 7, 5], [8, 3, 2], [3, 8, 5]]])
print(f"To get TENSOR: {TENSOR}")
print(f"To get TENSOR dimension: {TENSOR.ndim}")
print(f"To get TENSOR shape: {TENSOR.shape}: we have 2 matrixs of 3 x 3")
print(f"To get TENSOR first matrix: {TENSOR[0]}")
print(f"To get TENSOR first element of the first matrix: {TENSOR[0][0]}")

To get TENSOR: tensor([[[1, 5, 8],
         [9, 3, 9],
         [7, 8, 2]],

        [[5, 7, 5],
         [8, 3, 2],
         [3, 8, 5]]])
To get TENSOR dimension: 3
To get TENSOR shape: torch.Size([2, 3, 3]): we have 2 matrixs of 3 x 3
To get TENSOR first matrix: tensor([[1, 5, 8],
        [9, 3, 9],
        [7, 8, 2]])
To get TENSOR first element of the first matrix: tensor([1, 5, 8])


### Random tensors

Why random tensors?

Random tensors are important because the way many neural netowrks learn is that they start with tensors full of random numbers and adjust those random numbers to better represent the data.

`Start with random number -> look at data -> update random numbers -> look at data -> update random numbers...`

[torch.rand documentation](https://pytorch.org/docs/main/generated/torch.rand.html)

In [7]:
# Create a random tensor of size (3, 4, 2)
random_tensor = torch.rand(3, 4, 2)
random_tensor

tensor([[[0.6799, 0.1617],
         [0.5368, 0.7240],
         [0.0240, 0.9245],
         [0.1677, 0.4669]],

        [[0.4332, 0.1771],
         [0.6948, 0.1177],
         [0.5541, 0.2001],
         [0.0620, 0.1262]],

        [[0.2815, 0.7957],
         [0.5852, 0.6906],
         [0.0250, 0.5789],
         [0.3622, 0.8421]]])

In [8]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))
print(f"Dimension: {random_image_size_tensor.ndim}")
print(f"Shape: {random_image_size_tensor.shape}")

Dimension: 3
Shape: torch.Size([3, 224, 224])



## Zeros and Ones

In [9]:
## Create a tensor of all zeros
zeros = torch.zeros(size=(2,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
## Create a tensor of all ones
ones = torch.ones(size=(2,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
ones.dtype

torch.float32

## Create a range of tensors and tensors-like

[torch.range documentation](https://pytorch.org/docs/stable/generated/torch.range.html) DEPRECATED.

In [12]:
### Use torch.range
one_to_ten = torch.arange(1, 10)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
## Creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

[Tensor datatypes](https://pytorch.org/docs/stable/tensors.html#data-types)

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [14]:
torch.cuda.is_available()

True

In [15]:
# Float 32 Tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # default is float32, you can change it by passing torch.float16, for example
                               device=None, # could be "cuda", "cpu"
                               requires_grad=False) # if you want pytorch to track the gradients with these tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [16]:
float_32_tensor.dtype

torch.float32

In [17]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [18]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [19]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [20]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Getting information about tensors

1. Tensors not right datatype -> `tensor.dtype`
2. Tensors not right shape -> `tensor.shape`
3. Tensors not on the right device -> `tensor.device`

In [21]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1538, 0.1763, 0.0573, 0.7467],
        [0.1524, 0.7700, 0.9819, 0.3420],
        [0.5563, 0.9743, 0.6368, 0.7529]])

In [22]:
# Find out some details about tensor
print(f"{some_tensor}")
print(f"Data type of tensor: {some_tensor.dtype}")
print(f"Data shape of tensor: {some_tensor.shape}")
print(f"Data device of tensor: {some_tensor.device}")

tensor([[0.1538, 0.1763, 0.0573, 0.7467],
        [0.1524, 0.7700, 0.9819, 0.3420],
        [0.5563, 0.9743, 0.6368, 0.7529]])
Data type of tensor: torch.float32
Data shape of tensor: torch.Size([3, 4])
Data device of tensor: cpu


## Manipulating tensors

Tensors operations include:
* Addition
* Substraction
* Multiplication (element wise)
* Division
* Matrix multiplication

In [23]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [24]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [25]:
# Substract
tensor - 10

tensor([-9, -8, -7])

In [26]:
# Try pytorch built-in functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [27]:
torch.add(tensor, 10)

tensor([11, 12, 13])

## Matrix multiplication

Two main ways of performing multiplication in neuronal networks and deep learning
* Element-wise multiplitication
* Matrix multiplication (dot product: always returns a scalar)

There are two main rules that performing matrix needs to satisfy:
* The **inner dimension** should match
* The resulting matrix has the shape of the **outer dimension**

In [28]:
## Element-wise multiplication
print(f"{tensor} * {tensor}")
print("equals: ", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals:  tensor([1, 4, 9])


In [29]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [30]:
tensor @ tensor # Its the same

tensor(14)

## Finding the min, max, sum, etc (tensor aggregation)

In [31]:
# Create tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [32]:
torch.min(x)

tensor(0)

In [33]:
x.min()

tensor(0)

In [34]:
# Find de max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [35]:
# Find the mean
# NOTE: the mean functions required a tensor of float32 to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [36]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [37]:
# Finding the positional min and max
x.argmin()  # Index of the minimum value

tensor(0)

In [38]:
x.argmax()  # Index of the maximum value

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other ([vstack](https://pytorch.org/docs/stable/generated/torch.vstack.html)) or side by side ([hstack](https://pytorch.org/docs/stable/generated/torch.hstack.html))
* Squeeze - remove all `1` dimensiones from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [39]:
# Create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [40]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [41]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [42]:
# Chainging z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [43]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [44]:
# Squeezing a tensor
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [45]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New tensor: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New tensor: torch.Size([9])


In [46]:
# Unsqueeze
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New tensor: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New tensor: torch.Size([1, 9])


In [47]:
# Permute
x_original = torch.rand(size=(224, 224, 3))  # [height, width, color]
x_original.shape

torch.Size([224, 224, 3])

In [48]:
x_permuted = torch.permute(x_original, (2, 0, 1)) # [color, height, width]
x_permuted.shape

torch.Size([3, 224, 224])

## Indexing (select data)

Indexing with PyTorch is similar to indexing with Numpy.

In [49]:
# Create tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [50]:
# Indexing our tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [51]:
x[0, 0]

tensor([1, 2, 3])

In [52]:
x[0, 1, 1]

tensor(5)

In [53]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [54]:
x[:, 0:2]

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [55]:
x[0, 0, :]

tensor([1, 2, 3])

## PyTorch tensors and NumPy

In [56]:
# Numpy array to tensor
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # WRN: When converting from numpy to pytorch, it has de default data type from numpy
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [57]:
array.dtype

dtype('float64')

In [58]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [59]:
# A change in the value of array, does NOT change values in tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [60]:
# Tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [61]:
# A change in the value of tensor, does NOT change values in array
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility

To reduce the randomness in neural networks, comes the concept of a **random seed**

In [62]:
# Create 2 random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

random_tensor_A == random_tensor_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [63]:
# Reproducible tensors by setting seeds
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

random_tensor_C == random_tensor_D

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])